### ISSUE TITLE
Setup wizard: Share variables with multiple services

### ISSUE THREAD

**Issue by TripleSpeeder** [dappnode/DAppNodeSDK#124]
**Is your feature request related to a problem? Please describe.**
I'm working on a package that consists of multiple services. Each service needs to be provided with the same Ethereum endpoint. I'm using the setup wizard to help people setting this up.

The problem: I need to make separate fields for each service. So the user needs to set up the identical ethereum endpoint 3 times.

**Describe the solution you'd like**

I would like the `service` field to be an array of strings. This way I can specify that a field targets multiple services. Something like this:

```yml
fields:
  - id: ethereum_url
  - target:
    - type: environment
    - name: ETHEREUM_URL
    - services: 
      - "service1"
      - "service2"
      - "service3"
```

As a result the setup wizard will show only one field for specifying ETHEREUM_URL, but this setting will be applied to all services. This requires that all services use the exact same name for the env variable.

**Comment by dapplion** [comment]
Thanks for reporting! That's a very important feature for multi-service packages. What would you think about these options?

1. Multiple services (yours)
```yaml
fields:
  - id: ethereum_url
    target:
      type: environment
      name: ETHEREUM_URL
      services: ["service1", "service2", "service3"]
```

2. Multiple targets per field
```yaml
fields:
  - id: ethereum_url
    targets:
      - type: environment
        name: ETHEREUM_URL
        services: "service1"
      - type: environment
        name: ETHEREUM_URL_SOMETHING
        services: "service2"
```

3. Apply to all services with that ENV if no service is present
```yaml
fields:
  - id: ethereum_url
    target:
      type: environment
      name: ETHEREUM_URL
```
